project:
  type: website
  resources:
   - assets/*

website:
  title: "Open Science Workflow Training for ISC"
  reader-mode: true
  site-url: "https://moshima-pifsc.github.io/2025-01-ISC-OpenScienceTraining-dev" 
  repo-url: "https://github.com/MOshima-PIFSC/2025-01-ISC-OpenScienceTraining-dev"
  repo-actions: [source, issue]
  search: true
  back-to-top-navigation: true
  bread-crumbs: false
  sidebar:
    collapse-level: 1
    style: "floating"
    search: true
    tools:
      - icon: github
        href: https://github.com/MOshima-PIFSC/ISC_OSworkflow_training
    contents: 
      - text: "Home"
        file: index.qmd
      - section: "Day 1"  
        contents: 
        - text: "Welcome"
          file: assets/day-1-welcome.qmd
        - text: "Codespaces and VS Code"
          file: assets/day-1-pres-codespaces.qmd
      - section: "References"  
        contents: 
        - text: "Cheatsheet"
          file: assets/ref-Open_Science_Cheat_Sheet.qmd
      - section: "Contact us"
        contents:
        - text: "Nicholas Ducharme-Barth"
          file: assets/web-about-nd.qmd
        - text: "Megumi Oshima"
          file: assets/web-about-mo.qmd
      - section: "Support"
        contents:
        - text: "Submit an issue"
          href: https://github.com/MOshima-PIFSC/ISC_OSworkflow_training/issues/new/choose

format: 
  html:
    toc: true
    toc-expand: false
    theme:
      - default
      - assets/customizations/website-custom.scss
