# AI assistant for Shiny: https://gallery.shinyapps.io/assistant/)
# Examples were generated by the AI assistant using the following prompts:

#____________________________________________________________________________________________________________________
# - Create an app that shows a von Bertalanffy growth curve
library(bslib)
library(ggplot2)

# Von Bertalanffy growth function
vb_growth <- function(t, Linf, K, t0) {
  Linf * (1 - exp(-K * (t - t0)))
}

ui <- page_sidebar(
  title = "Von Bertalanffy Growth Curve",
  sidebar = sidebar(
    numericInput("Linf", "Asymptotic Length (Linf)", value = 100, min = 0),
    numericInput("K", "Growth Coefficient (K)", value = 0.3, min = 0, max = 1, step = 0.1),
    numericInput("t0", "Theoretical Age at Length 0 (t0)", value = -0.5, step = 0.1),
    hr(),
    helpText("The von Bertalanffy growth function describes how the length of a fish changes with age.")
  ),
  card(
    card_header("Growth Curve"),
    plotOutput("growth_plot")
  )
)

server <- function(input, output) {
  output$growth_plot <- renderPlot({
    # Generate age sequence
    age <- seq(0, 15, length.out = 100)
    
    # Calculate lengths
    length <- vb_growth(age, input$Linf, input$K, input$t0)
    
    # Create data frame
    df <- data.frame(Age = age, Length = length)
    
    # Plot
    ggplot(df, aes(x = Age, y = Length)) +
      geom_line(color = "blue", linewidth = 1.2) +
      labs(
        x = "Age",
        y = "Length",
        title = "Von Bertalanffy Growth Curve"
      ) +
      theme_minimal() +
      theme(
        plot.title = element_text(hjust = 0.5),
        text = element_text(size = 14)
      )
  })
}

shinyApp(ui, server)


#____________________________________________________________________________________________________________________
# - Create an app that generates data from a von Bertalanffy growth curve and plots it

library(bslib)
library(ggplot2)

# Von Bertalanffy growth function with random noise
vb_growth_with_noise <- function(t, Linf, K, t0, sd) {
  # Generate perfect curve
  length <- Linf * (1 - exp(-K * (t - t0)))
  # Add random normal noise
  length + rnorm(length(t), mean = 0, sd = sd)
}

ui <- page_sidebar(
  title = "Von Bertalanffy Growth Curve Simulator",
  sidebar = sidebar(
    numericInput("n_points", "Number of Data Points", value = 50, min = 10, max = 1000),
    numericInput("Linf", "Asymptotic Length (Linf)", value = 100, min = 0),
    numericInput("K", "Growth Coefficient (K)", value = 0.3, min = 0, max = 1, step = 0.1),
    numericInput("t0", "Theoretical Age at Length 0 (t0)", value = -0.5, step = 0.1),
    numericInput("sd", "Noise Level (SD)", value = 5, min = 0, step = 1),
    actionButton("generate", "Generate New Data", class = "btn-primary"),
    hr(),
    helpText("This app simulates length-at-age data following a von Bertalanffy growth curve with random noise.")
  ),
  card(
    card_header("Simulated Growth Data"),
    plotOutput("growth_plot")
  )
)

server <- function(input, output) {
  # Reactive value to store the generated data
  sim_data <- reactiveVal()
  
  # Generate new data when button is clicked
  observeEvent(input$generate, {
    # Generate random ages between 0 and 15
    age <- runif(input$n_points, 0, 15)
    
    # Calculate lengths with noise
    length <- vb_growth_with_noise(age, input$Linf, input$K, input$t0, input$sd)
    
    # Store in data frame
    sim_data(data.frame(Age = age, Length = length))
  })
  
  # Initialize data on startup
  observe({
    if (is.null(sim_data())) {
      age <- runif(input$n_points, 0, 15)
      length <- vb_growth_with_noise(age, input$Linf, input$K, input$t0, input$sd)
      sim_data(data.frame(Age = age, Length = length))
    }
  })
  
  # Plot the data
  output$growth_plot <- renderPlot({
    req(sim_data())
    
    # Generate theoretical curve for comparison
    age_seq <- seq(0, 15, length.out = 100)
    length_seq <- input$Linf * (1 - exp(-input$K * (age_seq - input$t0)))
    curve_df <- data.frame(Age = age_seq, Length = length_seq)
    
    ggplot() +
      # Add theoretical curve
      geom_line(data = curve_df, aes(x = Age, y = Length),
                color = "blue", linewidth = 1.2, alpha = 0.5) +
      # Add scattered points
      geom_point(data = sim_data(), aes(x = Age, y = Length),
                color = "red", alpha = 0.6) +
      labs(
        x = "Age",
        y = "Length",
        title = "Simulated Von Bertalanffy Growth Data",
        subtitle = "Blue line = theoretical curve, Red points = simulated data"
      ) +
      theme_minimal() +
      theme(
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        text = element_text(size = 14)
      )
  })
}

shinyApp(ui, server)

#____________________________________________________________________________________________________________________
# - Create an app that generates data from a two-sex von Bertalanffy growth curve and plots it
library(shiny)
library(bslib)
library(ggplot2)

# Two-sex Von Bertalanffy growth function with random noise
vb_growth_with_noise <- function(t, Linf, K, t0, sd, sex) {
  # Generate perfect curve (different parameters for each sex)
  if (sex == "Female") {
    length <- Linf[1] * (1 - exp(-K[1] * (t - t0[1])))
  } else {
    length <- Linf[2] * (1 - exp(-K[2] * (t - t0[2])))
  }
  # Add random normal noise
  length + rnorm(length(t), mean = 0, sd = sd)
}

ui <- page_sidebar(
  title = "Two-Sex Von Bertalanffy Growth Curve Simulator",
  sidebar = sidebar(
    numericInput("n_points", "Number of Data Points per Sex", value = 50, min = 10, max = 1000),
    
    # Female parameters
    h3("Female Parameters"),
    numericInput("Linf_f", "Female Asymptotic Length (Linf)", value = 120, min = 0),
    numericInput("K_f", "Female Growth Coefficient (K)", value = 0.25, min = 0, max = 1, step = 0.1),
    numericInput("t0_f", "Female t0", value = -0.5, step = 0.1),
    
    # Male parameters
    h3("Male Parameters"),
    numericInput("Linf_m", "Male Asymptotic Length (Linf)", value = 100, min = 0),
    numericInput("K_m", "Male Growth Coefficient (K)", value = 0.3, min = 0, max = 1, step = 0.1),
    numericInput("t0_m", "Male t0", value = -0.5, step = 0.1),
    
    # Common parameters
    numericInput("sd", "Noise Level (SD)", value = 5, min = 0, step = 1),
    actionButton("generate", "Generate New Data", class = "btn-primary"),
    hr(),
    helpText("This app simulates length-at-age data for males and females following separate von Bertalanffy growth curves.")
  ),
  card(
    card_header("Simulated Growth Data by Sex"),
    plotOutput("growth_plot")
  )
)

server <- function(input, output) {
  # Reactive value to store the generated data
  sim_data <- reactiveVal()
  
  # Generate new data when button is clicked
  observeEvent(input$generate, {
    # Generate random ages between 0 and 15 for both sexes
    age_f <- runif(input$n_points, 0, 15)
    age_m <- runif(input$n_points, 0, 15)
    
    # Calculate lengths with noise for both sexes
    length_f <- vb_growth_with_noise(
      age_f, 
      Linf = c(input$Linf_f, input$Linf_m),
      K = c(input$K_f, input$K_m),
      t0 = c(input$t0_f, input$t0_m),
      sd = input$sd,
      sex = "Female"
    )
    
    length_m <- vb_growth_with_noise(
      age_m,
      Linf = c(input$Linf_f, input$Linf_m),
      K = c(input$K_f, input$K_m),
      t0 = c(input$t0_f, input$t0_m),
      sd = input$sd,
      sex = "Male"
    )
    
    # Combine data
    df_f <- data.frame(Age = age_f, Length = length_f, Sex = "Female")
    df_m <- data.frame(Age = age_m, Length = length_m, Sex = "Male")
    sim_data(rbind(df_f, df_m))
  })
  
  # Initialize data on startup
  observe({
    if (is.null(sim_data())) {
      age_f <- runif(input$n_points, 0, 15)
      age_m <- runif(input$n_points, 0, 15)
      
      length_f <- vb_growth_with_noise(
        age_f,
        Linf = c(input$Linf_f, input$Linf_m),
        K = c(input$K_f, input$K_m),
        t0 = c(input$t0_f, input$t0_m),
        sd = input$sd,
        sex = "Female"
      )
      
      length_m <- vb_growth_with_noise(
        age_m,
        Linf = c(input$Linf_f, input$Linf_m),
        K = c(input$K_f, input$K_m),
        t0 = c(input$t0_f, input$t0_m),
        sd = input$sd,
        sex = "Male"
      )
      
      df_f <- data.frame(Age = age_f, Length = length_f, Sex = "Female")
      df_m <- data.frame(Age = age_m, Length = length_m, Sex = "Male")
      sim_data(rbind(df_f, df_m))
    }
  })
  
  # Plot the data
  output$growth_plot <- renderPlot({
    req(sim_data())
    
    # Generate theoretical curves for comparison
    age_seq <- seq(0, 15, length.out = 100)
    
    # Female curve
    length_seq_f <- input$Linf_f * (1 - exp(-input$K_f * (age_seq - input$t0_f)))
    curve_df_f <- data.frame(Age = age_seq, Length = length_seq_f, Sex = "Female")
    
    # Male curve
    length_seq_m <- input$Linf_m * (1 - exp(-input$K_m * (age_seq - input$t0_m)))
    curve_df_m <- data.frame(Age = age_seq, Length = length_seq_m, Sex = "Male")
    
    curve_df <- rbind(curve_df_f, curve_df_m)
    
    ggplot() +
      # Add theoretical curves
      geom_line(data = curve_df, aes(x = Age, y = Length, color = Sex),
                linewidth = 1.2, alpha = 0.5) +
      # Add scattered points
      geom_point(data = sim_data(), aes(x = Age, y = Length, color = Sex),
                alpha = 0.6) +
      scale_color_manual(values = c("Female" = "#FF69B4", "Male" = "#4169E1")) +
      labs(
        x = "Age",
        y = "Length",
        title = "Two-Sex Von Bertalanffy Growth Data",
        subtitle = "Lines = theoretical curves, Points = simulated data"
      ) +
      theme_minimal() +
      theme(
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        text = element_text(size = 14),
        legend.position = "top"
      )
  })
}

shinyApp(ui, server)


#____________________________________________________________________________________________________________________
# - Create an app that generates data from a two-sex von Bertalanffy growth curve with lognormal error and plots it

library(shiny)
library(bslib)
library(ggplot2)

# Two-sex Von Bertalanffy growth function with lognormal error
vb_growth_with_lognormal_error <- function(t, Linf, K, t0, cv, sex) {
  # Generate perfect curve (different parameters for each sex)
  if (sex == "Female") {
    mu <- Linf[1] * (1 - exp(-K[1] * (t - t0[1])))
  } else {
    mu <- Linf[2] * (1 - exp(-K[2] * (t - t0[2])))
  }
  # Add lognormal error
  # Convert CV to sigma parameter for lognormal distribution
  sigma <- sqrt(log(1 + cv^2))
  mu_log <- log(mu) - (sigma^2)/2
  exp(rnorm(length(t), mean = mu_log, sd = sigma))
}

ui <- page_sidebar(
  title = "Two-Sex Von Bertalanffy Growth Curve with Lognormal Error",
  sidebar = sidebar(
    numericInput("n_points", "Number of Data Points per Sex", value = 50, min = 10, max = 1000),
    
    # Female parameters
    h3("Female Parameters"),
    numericInput("Linf_f", "Female Asymptotic Length (Linf)", value = 120, min = 0),
    numericInput("K_f", "Female Growth Coefficient (K)", value = 0.25, min = 0, max = 1, step = 0.1),
    numericInput("t0_f", "Female t0", value = -0.5, step = 0.1),
    
    # Male parameters
    h3("Male Parameters"),
    numericInput("Linf_m", "Male Asymptotic Length (Linf)", value = 100, min = 0),
    numericInput("K_m", "Male Growth Coefficient (K)", value = 0.3, min = 0, max = 1, step = 0.1),
    numericInput("t0_m", "Male t0", value = -0.5, step = 0.1),
    
    # Common parameters
    numericInput("cv", "Coefficient of Variation", value = 0.1, min = 0, max = 1, step = 0.05),
    actionButton("generate", "Generate New Data", class = "btn-primary"),
    hr(),
    helpText("This app simulates length-at-age data with multiplicative lognormal error.")
  ),
  card(
    card_header("Simulated Growth Data by Sex"),
    plotOutput("growth_plot")
  )
)

server <- function(input, output) {
  # Reactive value to store the generated data
  sim_data <- reactiveVal()
  
  # Generate new data when button is clicked
  observeEvent(input$generate, {
    # Generate random ages between 0 and 15 for both sexes
    age_f <- runif(input$n_points, 0, 15)
    age_m <- runif(input$n_points, 0, 15)
    
    # Calculate lengths with lognormal error for both sexes
    length_f <- vb_growth_with_lognormal_error(
      age_f, 
      Linf = c(input$Linf_f, input$Linf_m),
      K = c(input$K_f, input$K_m),
      t0 = c(input$t0_f, input$t0_m),
      cv = input$cv,
      sex = "Female"
    )
    
    length_m <- vb_growth_with_lognormal_error(
      age_m,
      Linf = c(input$Linf_f, input$Linf_m),
      K = c(input$K_f, input$K_m),
      t0 = c(input$t0_f, input$t0_m),
      cv = input$cv,
      sex = "Male"
    )
    
    # Combine data
    df_f <- data.frame(Age = age_f, Length = length_f, Sex = "Female")
    df_m <- data.frame(Age = age_m, Length = length_m, Sex = "Male")
    sim_data(rbind(df_f, df_m))
  })
  
  # Initialize data on startup
  observe({
    if (is.null(sim_data())) {
      age_f <- runif(input$n_points, 0, 15)
      age_m <- runif(input$n_points, 0, 15)
      
      length_f <- vb_growth_with_lognormal_error(
        age_f,
        Linf = c(input$Linf_f, input$Linf_m),
        K = c(input$K_f, input$K_m),
        t0 = c(input$t0_f, input$t0_m),
        cv = input$cv,
        sex = "Female"
      )
      
      length_m <- vb_growth_with_lognormal_error(
        age_m,
        Linf = c(input$Linf_f, input$Linf_m),
        K = c(input$K_f, input$K_m),
        t0 = c(input$t0_f, input$t0_m),
        cv = input$cv,
        sex = "Male"
      )
      
      df_f <- data.frame(Age = age_f, Length = length_f, Sex = "Female")
      df_m <- data.frame(Age = age_m, Length = length_m, Sex = "Male")
      sim_data(rbind(df_f, df_m))
    }
  })
  
  # Plot the data
  output$growth_plot <- renderPlot({
    req(sim_data())
    
    # Generate theoretical curves for comparison
    age_seq <- seq(0, 15, length.out = 100)
    
    # Female curve
    length_seq_f <- input$Linf_f * (1 - exp(-input$K_f * (age_seq - input$t0_f)))
    curve_df_f <- data.frame(Age = age_seq, Length = length_seq_f, Sex = "Female")
    
    # Male curve
    length_seq_m <- input$Linf_m * (1 - exp(-input$K_m * (age_seq - input$t0_m)))
    curve_df_m <- data.frame(Age = age_seq, Length = length_seq_m, Sex = "Male")
    
    curve_df <- rbind(curve_df_f, curve_df_m)
    
    ggplot() +
      # Add theoretical curves
      geom_line(data = curve_df, aes(x = Age, y = Length, color = Sex),
                linewidth = 1.2, alpha = 0.5) +
      # Add scattered points
      geom_point(data = sim_data(), aes(x = Age, y = Length, color = Sex),
                alpha = 0.6) +
      scale_color_manual(values = c("Female" = "#FF69B4", "Male" = "#4169E1")) +
      labs(
        x = "Age",
        y = "Length",
        title = "Two-Sex Von Bertalanffy Growth Data",
        subtitle = "Lines = theoretical curves, Points = simulated data with lognormal error"
      ) +
      theme_minimal() +
      theme(
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        text = element_text(size = 14),
        legend.position = "top"
      )
  })
}

shinyApp(ui, server)

